### ISSUE TITLE
Playlist import errors

### ISSUE THREAD

**Issue by NomadicDaggy** [NomadicDaggy/spotify-playlist-lookup#30]
spotify-playlist-lookup-db-1               | 2022-09-14 18:41:07.989 UTC [1200028] ERROR:  value too long for type character varying(1000)
spotify-playlist-lookup-db-1               | 2022-09-14 18:41:07.989 UTC [1200028] STATEMENT:  INSERT INTO playlists (spotify_id, name, description, image_url, owner_name) VALUES ('4BXMH7TLydNEXR5awGJ65g', 'The Sound of Ukrainian Hip Hop', 'See also <a href="spotify:playlist:0y5B0T4o3rQVL710kYMiiV">Intro</a>, <a href="spotify:playlist:6QShHaHejghLUUe2dFG9g6">Pulse</a>, <a href="spotify:playlist:2g5tzog0WvgfwaV5JxNhSR">Edge</a> or <a href="spotify:playlist:5Q5GWnulCkgrYVFtUIAAPt">2021</a>; or the Sounds of <a href="spotify:playlist:6S0frS33YQdbRp0JH93cut">Ukrainian Pop</a>, <a href="spotify:playlist:2TsSOQsGVFwKfOZLra0x4E">Ukrainian Rock</a>, <a href="spotify:playlist:62iU93fUNvuhYsmVAZGk8f">BC Underground Hip Hop</a>, <a href="spotify:playlist:5pLrIA7efzz23RMrQUiMFt">Rap Cristão</a>, <a href="spotify:playlist:2Wk6e4zTLTYFofSDgprBgB">Armenian Hip Hop</a>, <a href="spotify:playlist:1eTqeJPyDOv3O44cMPOp7Y">Rap Gaúcho</a>, <a href="spotify:playlist:7zBydkoj9qpNmelxR9goHB">Arabic Hip Hop</a>, <a href="spotify:playlist:7osrkj0fpqswzvJuTvhpLF">Ugandan Hip Hop</a>, <a href="spotify:playlist:30xIDBWMvRjMTGCssgd0hp">Rap Algérien</a> or <a href="spotify:playlist:6gpELhsiYJyaL13srOlTMQ">Urbano Español</a>; or much more at <a href="http://everynoise.com">everynoise.com</a>.', 'https://i.scdn.co/image/ab67706c0000bebbc215c4748998e44322b4cf04', 'The Sounds of Spotify') RETURNING playlists.id
spotify-playlist-lookup-api-worker01-1     | [2022-09-14 18:41:08,004: ERROR/ForkPoolWorker-1] Task tasks.process_data[b4862ccb-6be5-4333-b071-15559932b298] raised unexpected: DataError('(psycopg2.errors.StringDataRightTruncation) value too long for type character varying(1000)\n')
spotify-playlist-lookup-api-worker01-1     | Traceback (most recent call last):
spotify-playlist-lookup-api-worker01-1     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
spotify-playlist-lookup-api-worker01-1     |     self.dialect.do_execute(
spotify-playlist-lookup-api-worker01-1     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
spotify-playlist-lookup-api-worker01-1     |     cursor.execute(statement, parameters)
spotify-playlist-lookup-api-worker01-1     | psycopg2.errors.StringDataRightTruncation: value too long for type character varying(1000)
spotify-playlist-lookup-api-worker01-1     | 
spotify-playlist-lookup-api-worker01-1     | 
spotify-playlist-lookup-api-worker01-1     | The above exception was the direct cause of the following exception:
spotify-playlist-lookup-api-worker01-1     | 
spotify-playlist-lookup-api-worker01-1     | Traceback (most recent call last):
spotify-playlist-lookup-api-worker01-1     |   File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 451, in trace_task
spotify-playlist-lookup-api-worker01-1     |     R = retval = fun(*args, **kwargs)
spotify-playlist-lookup-api-worker01-1     |   File "/usr/src/app/app/__init__.py", line 54, in __call__
spotify-playlist-lookup-api-worker01-1     |     return self.run(*args, **kwargs)
spotify-playlist-lookup-api-worker01-1     |   File "/usr/src/app/tasks/__init__.py", line 20, in process_data
spotify-playlist-lookup-api-worker01-1     |     insert_playlists_tracks(playlist_data)
spotify-playlist-lookup-api-worker01-1     |   File "/usr/src/app/app/models.py", line 172, in insert_playlists_tracks
spotify-playlist-lookup-api-worker01-1     |     db.session.flush()
spotify-playlist-lookup-api-worker01-1     |   File "<string>", line 2, in flush
spotify-playlist-lookup-api-worker01-1     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3386, in flush
spotify-playlist-lookup-api-worker01-1     |     self._flush(objects)
spotify-playlist-lookup-api-worker01-1     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3526, in _flush
spotify-playlist-lookup-api-worker01-1     |     transaction.rollback(_capture_exception=True)
spotify-playlist-lookup-api-worker01-1     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
spotify-playlist-lookup-api-worker01-1     |     compat.raise_(
spotify-playlist-lookup-api-worker01-1     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
spotify-playlist-lookup-api-worker01-1     |     raise exception
spotify-playlist-lookup-api-worker01-1     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3486, in _flush
spotify-playlist-lookup-api-worker01-1     |     flush_context.execute()
spotify-playlist-lookup-api-worker01-1     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
spotify-playlist-lookup-api-worker01-1     |     rec.execute(self)
spotify-playlist-lookup-api-worker01-1     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
spotify-playlist-lookup-api-worker01-1     |     util.preloaded.orm_persistence.save_obj(
spotify-playlist-lookup-api-worker01-1     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
spotify-playlist-lookup-api-worker01-1     |     _emit_insert_statements(
spotify-playlist-lookup-api-worker01-1     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 1238, in _emit_insert_statements
spotify-playlist-lookup-api-worker01-1     |     result = connection._execute_20(
spotify-playlist-lookup-api-worker01-1     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
spotify-playlist-lookup-api-worker01-1     |     return meth(self, args_10style, kwargs_10style, execution_options)
spotify-playlist-lookup-api-worker01-1     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 333, in _execute_on_connection
spotify-playlist-lookup-api-worker01-1     |     return connection._execute_clauseelement(
spotify-playlist-lookup-api-worker01-1     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
spotify-playlist-lookup-api-worker01-1     |     ret = self._execute_context(
spotify-playlist-lookup-api-worker01-1     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
spotify-playlist-lookup-api-worker01-1     |     self._handle_dbapi_exception(
spotify-playlist-lookup-api-worker01-1     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
spotify-playlist-lookup-api-worker01-1     |     util.raise_(
spotify-playlist-lookup-api-worker01-1     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
spotify-playlist-lookup-api-worker01-1     |     raise exception
spotify-playlist-lookup-api-worker01-1     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
spotify-playlist-lookup-api-worker01-1     |     self.dialect.do_execute(
spotify-playlist-lookup-api-worker01-1     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
spotify-playlist-lookup-api-worker01-1     |     cursor.execute(statement, parameters)
spotify-playlist-lookup-api-worker01-1     | sqlalchemy.exc.DataError: (psycopg2.errors.StringDataRightTruncation) value too long for type character varying(1000)
spotify-playlist-lookup-api-worker01-1     | 
spotify-playlist-lookup-api-worker01-1     | [SQL: INSERT INTO playlists (spotify_id, name, description, image_url, owner_name) VALUES (%(spotify_id)s, %(name)s, %(description)s, %(image_url)s, %(owner_name)s) RETURNING playlists.id]
spotify-playlist-lookup-api-worker01-1     | [parameters: {'spotify_id': '4BXMH7TLydNEXR5awGJ65g', 'name': 'The Sound of Ukrainian Hip Hop', 'description': 'See also <a href="spotify:playlist:0y5B0T4o3rQVL710kYMiiV">Intro</a>, <a href="spotify:playlist:6QShHaHejghLUUe2dFG9g6">Pulse</a>, <a href="spotify:p ... (742 characters truncated) ... rien</a> or <a href="spotify:playlist:6gpELhsiYJyaL13srOlTMQ">Urbano Español</a>; or much more at <a href="http://everynoise.com">everynoise.com</a>.', 'image_url': 'https://i.scdn.co/image/ab67706c0000bebbc215c4748998e44322b4cf04', 'owner_name': 'The Sounds of Spotify'}]
spotify-playlist-lookup-api-worker01-1     | (Background on this error at: https://sqlalche.me/e/14/9h9h)
spotify-playlist-lookup-api-worker01-1     | [2022-09-14 18:41:08,048: INFO/ForkPoolWorker-1] Processing data
spotify-playlist-lookup-api-worker01-1     | [2022-09-14 18:41:27,297: ERROR/ForkPoolWorker-1] Task tasks.process_data[d3d2df08-ad6e-456d-a806-417d9ff76f51] raised unexpected: ServiceUnavailable('Error in https://api.spotify.com/v1/playlists/2pEhg5mGvPMvvSwMngQCU6/tracks?limit=100&offset=400:\n503: Service unavailable\n')
spotify-playlist-lookup-api-worker01-1     | Traceback (most recent call last):
spotify-playlist-lookup-api-worker01-1     |   File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 451, in trace_task
spotify-playlist-lookup-api-worker01-1     |     R = retval = fun(*args, **kwargs)
spotify-playlist-lookup-api-worker01-1     |   File "/usr/src/app/app/__init__.py", line 54, in __call__
spotify-playlist-lookup-api-worker01-1     |     return self.run(*args, **kwargs)
spotify-playlist-lookup-api-worker01-1     |   File "/usr/src/app/tasks/__init__.py", line 18, in process_data
spotify-playlist-lookup-api-worker01-1     |     playlist_data = mp.get_data()
spotify-playlist-lookup-api-worker01-1     |   File "/usr/src/app/app/api_data_import.py", line 68, in get_data
spotify-playlist-lookup-api-worker01-1     |     self._format_track(t) for t in self._get_playlist_tracks_from_api()
spotify-playlist-lookup-api-worker01-1     |   File "/usr/src/app/app/api_data_import.py", line 30, in _get_playlist_tracks_from_api
spotify-playlist-lookup-api-worker01-1     |     p = self.spotify.playlist_items(
spotify-playlist-lookup-api-worker01-1     |   File "/usr/local/lib/python3.9/site-packages/tekore/_client/api/playlist/view.py", line 41, in wrapper
spotify-playlist-lookup-api-worker01-1     |     return function(self, *args, **kwargs)
spotify-playlist-lookup-api-worker01-1     |   File "/usr/local/lib/python3.9/site-packages/tekore/_sender/client.py", line 79, in wrapper
spotify-playlist-lookup-api-worker01-1     |     return post_func(request, response, *params)
spotify-playlist-lookup-api-worker01-1     |   File "/usr/local/lib/python3.9/site-packages/tekore/_client/decor/__init__.py", line 19, in parse_response
spotify-playlist-lookup-api-worker01-1     |     handle_errors(request, response)
spotify-playlist-lookup-api-worker01-1     |   File "/usr/local/lib/python3.9/site-packages/tekore/_client/decor/handle.py", line 33, in handle_errors
spotify-playlist-lookup-api-worker01-1     |     raise error_cls(error_str, request=request, response=response)
spotify-playlist-lookup-api-worker01-1     | tekore.ServiceUnavailable: Error in https://api.spotify.com/v1/playlists/2pEhg5mGvPMvvSwMngQCU6/tracks?limit=100&offset=400:
spotify-playlist-lookup-api-worker01-1     | 503: Service unavailable
spotify-playlist-lookup-api-worker01-1     | 
spotify-playlist-lookup-api-worker01-1     | [2022-09-14 18:41:27,325: ERROR/MainProcess] Task handler raised error: <MaybeEncodingError: Error sending result: '"(1, <ExceptionInfo: ServiceUnavailable('Error in https://api.spotify.com/v1/playlists/2pEhg5mGvPMvvSwMngQCU6/tracks?limit=100&offset=400:\\n503: Service unavailable\\n')>, None)"'. Reason: ''PicklingError("Can\'t pickle <class \'tekore.ServiceUnavailable\'>: it\'s not the same object as tekore.ServiceUnavailable")''.>
spotify-playlist-lookup-api-worker01-1     | Traceback (most recent call last):
spotify-playlist-lookup-api-worker01-1     |   File "/usr/local/lib/python3.9/site-packages/billiard/pool.py", line 366, in workloop
spotify-playlist-lookup-api-worker01-1     |     put((READY, (job, i, result, inqW_fd)))
spotify-playlist-lookup-api-worker01-1     |   File "/usr/local/lib/python3.9/site-packages/billiard/queues.py", line 366, in put
spotify-playlist-lookup-api-worker01-1     |     self.send_payload(ForkingPickler.dumps(obj))
spotify-playlist-lookup-api-worker01-1     |   File "/usr/local/lib/python3.9/site-packages/billiard/reduction.py", line 56, in dumps
spotify-playlist-lookup-api-worker01-1     |     cls(buf, protocol).dump(obj)
spotify-playlist-lookup-api-worker01-1     | billiard.pool.MaybeEncodingError: Error sending result: '"(1, <ExceptionInfo: ServiceUnavailable('Error in https://api.spotify.com/v1/playlists/2pEhg5mGvPMvvSwMngQCU6/tracks?limit=100&offset=400:\\n503: Service unavailable\\n')>, None)"'. Reason: ''PicklingError("Can\'t pickle <class \'tekore.ServiceUnavailable\'>: it\'s not the same object as tekore.ServiceUnavailable")''.

**Comment by NomadicDaggy** [comment]
Playlist descriptions need to be capped at 1000 chars before sending to db

**Comment by NomadicDaggy** [comment]
And tekore.ServiceUnavailable needs to be caught
